# UPPTIME configuration
#
# Follow these instructions to create a status page like https://github.com/GBIFes/status for your LA Portal:
#
#
# 1) Follow the https://upptime.js.org/docs/get-started/ instructions
# 2) copy the dot-upptimerc.yml as .upptimerc.yml in your uptime status created repository
# 3) Update the github owner/repo and for instance the icons in this configuration
# 4) That is

# Change these first
owner: GBIFes # Your GitHub organization or username, where this repository lives (for instance, biodiversiydata-se in the case of https://github.com/biodiversitydata-se)
repo: status # The name of this repository (for instance, like: https://github.com/GBIFes/status)


sites:
  - name: Web de GBIF.ES
    url: https://gbif.es
  - name: Portal de Datos de GBIF.ES
    url: https://datos.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Alerts service
    url: https://alertas.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
    maxRedirects: 10
  - name: Apikey service
    url: https://auth.gbif.es/apikey
  - name: CAS service
    url: https://auth.gbif.es/cas
    maxRedirects: 10
  - name: CAS management service
    url: https://auth.gbif.es/cas-management/
    maxRedirects: 10
  - name: Userdetails service
    url: https://auth.gbif.es/userdetails
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Species service (bie)
    url: https://especies.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Species web services (bie-index)
    url: https://especies-ws.gbif.es
  - name: Species test search
    url: https://especies.gbif.es/search?q=acacia
  - name: Species page
    url: https://especies.gbif.es/species/2978223    
  - name: Records service (biocache)
    url: https://registros.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Records test search
    url: https://registros.gbif.es/occurrences/search?q=taxa%3A%22acacia%22#tab_recordsView
  - name: Records web services (biocache-service)
    url: https://registros-ws.gbif.es
  - name: Collections service
    url: https://colecciones.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Collections web services
    url: https://colecciones.gbif.es/ws
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Dashboard service
    url: https://dashboard.gbif.es
  - name: Data quality service
    url: https://data-quality.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Data quality profiles
    url: https://data-quality.gbif.es/api/v1/data-profiles?enabled=true
  - name: DOI web services
    url: https://doi.gbif.es/api/
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: DOI service
    url: https://doi.gbif.es
  - name: Branding website
    url: https://datos.gbif.es/brand-2020-brunch
  - name: Image service
    url: https://imagenes.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Logger service
    url: https://logger.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Logger reasons url
    url: https://logger.gbif.es/service/logger/reasons
  - name: Namematching service
    url: https://name-matching.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Namematching service (correct name index)
    url: https://name-matching.gbif.es/api/search?q=Cenchrus%20setaceus
    __dangerous__body_down: "id.biodiversity.org.au"
  - name: Namematching service (correct basionyms)
    url: https://name-matching.gbif.es/api/search?q=Cenchrus%20setaceus
    __dangerous__body_down: "Morrone (Forssk.)"
  - name: Regions service
    url: https://regiones.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Sensitive service
    url: https://sds.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Spatial hub service
    url: https://espacial.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Spatial web service
    url: https://espacial.gbif.es/ws
  - name: Spatial fields
    url: https://espacial.gbif.es/ws/fields
  - name: Geoserver service
    url: https://espacial.gbif.es/geoserver
  - name: Species Lists service
    url: https://listas.gbif.es
  - name: Sensitive data service
    url: https://datos-sensibles.gbif.es
    __dangerous__body_down: "Tenemos algún problema temporal en nuestros servicios."
  - name: Sensitive data service (correct name index)
    url: https://datos-sensibles.gbif.es/api/isSensitive?scientificName=lynx%20pardinus
    __dangerous__body_down: "false"
  - name: IPT
    url: https://ipt.gbif.es
  - name: IPT demo
    url: https://ipt-demo.gbif.es
  - name: IPT demo plic
    url: https://ipt-demo-plic.gbif.es    
  - name: LA demo
    url: https://demo.gbif.es
  - name: eLearning GBIF.es
    url: https://elearning.gbif.es
  - name: Repositorio APT
    url: https://apt.gbif.es
  - name: Infraestructura Iberoamericana de Información sobre Biodiversidad
    url: https://recibio.net
  - name: Difusion
    url: https://difusion.gbif.es
  - name: CSIC Hub
    url: https://csic.gbif.es
  - name: Colecciones Botánicas Hub
    url: https://colecciones-botanicas.gbif.es/
  - name: Colecciones Marinas Hub
    url: https://colecciones-marinas.gbif.es/
  - name: mail service
    url: https://mail.gbif.es

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
  name: GBIF Spain service status
  introTitle: "Global Biodiversity Information Facility - Spain"
  introMessage: Live status page of GBIF Spain services
  navbar:
    - title: Status
      href: /
      icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# For instance, you can send notifications to a telegram group
#
# See https://upptime.js.org/docs/configuration


