# Change these first
owner: GBIFes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:

  - name: GBIF Spain
    url: https://gbif.es
  - name: Portal de Datos de GBIF.es
    url: https://datos.gbif.es
  - name: Colecciones de historia natural de España
    url: https://colecciones.gbif.es
  - name: Búsqueda de registros Portal de Datos de GBIF.ES
    url: https://registros.gbif.es
  - name: Registros Webservices
    url: https://registros-ws.gbif.es
  - name: Especies
    url: https://especies.gbif.es
  - name: Especies Webservices
    url: https://especies-ws.gbif.es
  - name: Regiones
    url: https://regiones.gbif.es
  - name: Listas de Especies
    url: https://listas.gbif.es
  - name: Portal Espacial
    url: https://espacial.gbif.es
  - name: Servicio de Imágenes
    url: https://imagenes.gbif.es
  - name: CAS
    url: https://auth.gbif.es/cas/
    expectedStatusCodes:
      - 302
  - name: Userdetails
    url: https://auth.gbif.es/userdetails/
  - name: Apikey
    url: https://auth.gbif.es/apikey/
  - name: CAS Management
    url: https://auth.gbif.es/cas-management/
    expectedStatusCodes:
      - 302
  - name: Servicio de DOI
    url: https://doi.gbif.es
  - name: Dashboard de GBIF.es
    url: https://dashboard.gbif.es
  - name: Alertas de GBIF.es
    url: https://alertas.gbif.es
    expectedStatusCodes:
      - 302
  - name: Logger
    url: https://logger.gbif.es
  - name: IPT
    url: https://ipt.gbif.es
  - name: IPT demo
    url: https://ipt.gbif.es
  - name: LA demo
    url: https://demo.gbif.es
  - name: eLearning GBIF.es
    url: https://elearning.gbif.es
  - name: Repositorio APT
    url: apt.gbif.es
  - name: Infraestructura Iberoamericana de Información sobre Biodiversidad
    url: https://recibio.net

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
  name: GBIF Spain service status
  introTitle: "Global Biodiversity Information Facility - Spain"
  introMessage: Live status page of GBIF Spain services
  navbar:
    - title: Status
      href: /    icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
