# UPPTIME configuration
#
# Follow these instructions to create a status page like https://github.com/GBIFes/status for your LA Portal:
#
#
# 1) Follow the https://upptime.js.org/docs/get-started/ instructions
# 2) copy the dot-upptimerc.yml as .upptimerc.yml in your uptime status created repository
# 3) Update the github owner/repo and for instance the icons in this configuration
# 4) That is

# Change these first
owner: GBIFes # Your GitHub organization or username, where this repository lives (for instance, biodiversiydata-se in the case of https://github.com/biodiversitydata-se)
repo: status # The name of this repository (for instance, like: https://github.com/GBIFes/status)


sites:
  - name: Portal de Datos de GBIF.ES
    url: https://gbif.es
  - name: Alerts service
    url: https://alertas.gbif.es
    maxRedirects: 10
  - name: Apikey service
    url: https://auth.gbif.es/apikey
  - name: CAS service
    url: https://auth.gbif.es/cas
    maxRedirects: 10
  - name: CAS management service
    url: https://auth.gbif.es/cas-management/
    maxRedirects: 10
  - name: Userdetails service
    url: https://auth.gbif.es/userdetails
  - name: Species service (bie)
    url: https://especies.gbif.es
  - name: Species web services (bie-index)
    url: https://especies-ws.gbif.es
  - name: Records service (biocache)
    url: https://registros.gbif.es
  - name: Records web services (biocache-service)
    url: https://registros-ws.gbif.es
  - name: Collections service
    url: https://colecciones.gbif.es
  - name: Collections web services
    url: https://colecciones.gbif.es/ws
  - name: Dashboard service
    url: https://dashboard.gbif.es
  - name: Data quality service
    url: https://data-quality.gbif.es
  - name: DOI web services
    url: https://doi.gbif.es/api/
  - name: DOI service
    url: https://doi.gbif.es
  - name: Branding website
    url: https://datos.gbif.es/brand-2020-brunch
  - name: Image service
    url: https://imagenes.gbif.es
  - name: Logger service
    url: https://logger.gbif.es
  - name: Logger reasons url
    url: https://logger.gbif.es/service/logger/reasons
  - name: Namematching service
    url: https://name-matching.gbif.es
  - name: Regions service
    url: https://regiones.gbif.es
  - name: Sensitive service
    url: https://sds.gbif.es
  - name: Spatial hub service
    url: https://espacial.gbif.es
  - name: Spatial web service
    url: https://espacial.gbif.es/ws
  - name: Spatial fields
    url: https://espacial.gbif.es/ws/fields
  - name: Geonetwork service
    url: https://espacial.gbif.es/geonetwork
  - name: Geoserver service
    url: https://espacial.gbif.es/geoserver
  - name: Species Lists service
    url: https://listas.gbif.es
  - name: IPT
    url: https://ipt.gbif.es
  - name: IPT demo
    url: https://ipt-demo.gbif.es
  - name: LA demo
    url: https://demo.gbif.es
  - name: eLearning GBIF.es
    url: https://elearning.gbif.es
  - name: Repositorio APT
    url: apt.gbif.es
  - name: Infraestructura Iberoamericana de Información sobre Biodiversidad
    url: https://recibio.net

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
  name: GBIF Spain service status
  introTitle: "Global Biodiversity Information Facility - Spain"
  introMessage: Live status page of GBIF Spain services
  navbar:
    - title: Status
      href: /
      icon: https://www.gbif.es/wp-content/uploads/2017/05/gbif-logo.svg
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# For instance, you can send notifications to a telegram group
#
# See https://upptime.js.org/docs/configuration


